jai/jai.py
=> bug fix similar

.github/workflows/publish-pypi.yml, .github/workflows/run-tests.yml, setup.py
Workflow para subir o pacote para o PyPi quando fizer um push na `main`.
=> Workflow para PyPi

.github/workflows/publish-pypi.yml
o filho chora mas a mãe não vê
=> Update publish-pypi.yml again again

.github/workflows/publish-pypi.yml
=> Update workflow (publish PyPi)

jai/jai.py
Whatever does not kill you, makes you stronger
=> fix auth API URL

jai/jai.py
Adição do parâmetro não obrigatório "company" no método _get-auth-key_
=> Adição de parametro no método get_auth_key

jai/processing.py
Added copy on process functions
=> Fix process

jai/jai.py
- Consertando o problema do target no sanity
resolves #117
=> Fixing 'target' in sanity method

jai/jai.py, jai/tests/test_zjai_errors.py
It is much easier to do the wrong thing... so we need to test if you are doing the wrong thing the right way
=> Testing exceptions and errors on JAI

jai/jai.py
Users can now define which kind of embedding they want on `fill` and `sanity` methods.
=> db_type for fill and sanity

jai/jai.py, setup.py
=> Overwrite re-fix

jai/functions/utils_funcs.py, jai/jai.py
Improved checking for corner case (predict with one column as feature) when using dtype `Supervised`. 
Fixes #167
=> further checks for supervised dtype

jai/jai.py, jai/tests/test_zjai_basics.py, jai/tests/test_zjai_errors.py, jai/tests/test_zjai_models.py
Trying to get back to 90% test coverage
=> More SDK testing

jai/jai.py
No changes in JAI-SDK was an overstatement...
=> Get database size from info property

.github/dependabot.yml, .github/workflows/run-tests.yml, .github/workflows/yapf-formatter.yml, docs/advanced/report.rst, jai/jai.py, jai/processing.py, jai/tests/test_process.py, jai/tests/test_zjai_errors.py, setup.py
- support/test python 3.9
- remove unused imports action
- print enhance
=> enhancements

jai/__init__.py, jai/base.py, jai/jai.py
- Implementation of the describe method
=> describe method

jai/jai.py, jai/tests/test_zjai_basics.py
- Removed validation checks from `.fields()` method, leaving this checks to be done internally in the api. Should be a good speedup.
- Improved get_dtypes
- Removed dropna in categorical columns if a lot of categories
=> removed checks from method fields

docs/source/jai_in_5_minutes_classification_with_iris.rst, docs/source/jai_in_5_minutes_fraud_detection.rst
We have built two classification examples that can be found on the following  paths:
- jai-sdk/docs/source/jai-in-5-minutes-fraud-detection.rst
- jai-sdk/docs/source/jai-in-5-minutes-classification-with-iris.rst
We believe we should have examples that explore more efficiently JAI's strengths.
=> Docs jai examples iza

docs/source/what_is_jai.rst
What is JAI + links funcionando
=> Laura nao consegue fazer docs

docs/conf.py, docs/source/1-overview/classification_with_iris.rst, docs/source/1-overview/fraud_detection.rst, docs/source/1-overview/getting_started.rst, docs/source/2-using_jai/fit.rst, docs/source/2-using_jai/remove_data.rst, docs/source/2-using_jai/using_environment.rst, docs/source/3-inference/predict.rst, docs/source/3-inference/similarity.rst, docs/source/use_cases/setup_data.rst, docs/source/use_cases/supervised.rst
Added `>>>` and `...` to python codes
=> Code boxes

jai/preprocessing.py
A new preprocessing function was added in order to allow users to convert unix timestamp to datetime timestamp.
=> Unix new function of preprocessing

jai/base.py, jai/functions/classes.py, jai/functions/utils_funcs.py, jai/functions/validations.py, jai/jai.py, jai/preprocessing.py, jai/processing.py, jai/tests/test_validations.py, requirements.txt
< Feel free to remove any unnecessary section for your pull request. >
[ ] Bug fixing
[X] New development
Consume part of recommendation. Setup is still to be developed.
=> Recommendation consume

jai/preprocessing.py
[ ] Bug fixing
Added warning to `split` when NA values are found.
=> Warn split

.github/workflows/run-tests.yml, requirements.txt, setup.py
[ ] Bug fixing
add support to python 3.10
=> support to python 3.10

docs/index.rst, docs/source/reference/fit_kwargs.rst, docs/source/reference/util_auth.rst, docs/source/task/explorer.rst, docs/source/task/linear.rst, docs/source/task/query.rst, docs/source/task/trainer.rst, docs/source/task/vectors.rst, docs/source/whats_new/older_versions.rst, docs/source/whats_new/v0.20.0.rst, jai/core/authentication.py, jai/core/jai.py, jai/task/base.py, jai/task/explorer.py, jai/task/linear.py, jai/task/query.py, jai/task/trainer.py, jai/task/vectors.py
=> Review fix

docs/source/whats_new/v0.20.0.rst
[ ] Bug fixing
Last corrections to release notes
=> fix release notes

README.md, docs/source/overview/classification_with_iris.rst, docs/source/reference/fit_kwargs.rst, jai/core/base.py, jai/task/linear.py
[ ] Bug fixing
fix README and some docs
=> Fix readme

docs/source/overview/whats_new.rst, docs/source/whats_new/v0.20.1.rst, jai/__init__.py, jai/core/base.py, jai/core/jai.py, jai/task/query.py
[ ] Bug fixing
prep for the new version
=> Version prep

jai/core/base.py, jai/task/linear.py, jai/tests/test_ztask_linear.py
In some situations, it's necessary to get the linear model weights.
This PR now permits a user to get some fitted model weights through a new JAI function available in `LinearModel` task method: `get_linear_model_weights`
Tests were already developed for this PR new implementations
=> Getting linear weights

jai/core/base.py, jai/core/jai.py, jai/task/base.py, jai/task/explorer.py, jai/task/linear.py, jai/task/query.py, jai/task/trainer.py, jai/task/vectors.py
< Feel free to remove any unnecessary section for your pull request. >
[ ] Bug fixing
Briefly describe the problem or reason why you have made this pull request.
When it's the case, describe the root cause of your problem.
Describe your code changes in detail for reviewers. Explain the technical solution you have provided and how it fixes the issue case.
Were unit test cases recorded for this fix, or was only manual testing applicable?
=> re-add auth_key parameter to all classes

docs/source/inference/predict.rst, docs/source/inference/similarity.rst, docs/source/use_cases/setup_data.rst, jai/core/base.py, jai/core/jai.py, jai/task/query.py, jai/task/trainer.py, jai/task/vectors.py, jai/types/generic.py, jai/types/hyperparams.py, jai/utilities/splits.py
< Feel free to remove any unnecessary section for your pull request. >
[X] Bug fixing
[X] New development
Briefly describe the problem or reason why you have made this pull request.
When it's the case, describe the root cause of your problem.
Describe your code changes in detail for reviewers. Explain the technical solution you have provided and how it fixes the issue case.
Were unit test cases recorded for this fix, or was only manual testing applicable?
=> New changes

jai/core/authentication.py
New parameters (work_email, company_size, phone, code_skills) needed to be implemented into API sign-up method.
=> Adapting JAI to new hubspot parameters

jai/core/utils_funcs.py, jai/core/validations.py, jai/types/generic.py
[ ] Bug fixing
[X] New development
Briefly describe the problem or reason why you have made this pull request.
When it's the case, describe the root cause of your problem.
Describe your code changes in detail for reviewers. Explain the technical solution you have provided and how it fixes the issue case.
Were unit test cases recorded for this fix, or was only manual testing applicable?
=> clip model

.github/workflows/run-tests.yml, jai/core/authentication.py, jai/core/base.py, jai/core/jai.py, jai/core/utils_funcs.py, jai/core/validations.py, jai/task/base.py, jai/task/explorer.py, jai/task/linear.py, jai/task/query.py, jai/task/trainer.py, jai/task/vectors.py, jai/tests/test_zjai_models.py, jai/tests/test_ztask_models.py, jai/tests/test_zzapplications.py, jai/types/hyperparams.py, jai/types/linear.py, jai/types/responses.py, jai/utilities/processing.py, jai/utilities/splits.py, requirements.txt, setup.py
< Feel free to remove any unnecessary section for your pull request. >
[X] Bug fixing
[X] New development
Briefly describe the problem or reason why you have made this pull request.
When it's the case, describe the root cause of your problem.
Describe your code changes in detail for reviewers. Explain the technical solution you have provided and how it fixes the issue case.
Were unit test cases recorded for this fix, or was only manual testing applicable?
=> new method & refactoration

jai/core/base.py, jai/core/validations.py, jai/task/explorer.py, jai/task/trainer.py, jai/types/hyperparams.py, jai/types/responses.py, jai/utilities/image.py, jai/utilities/splits.py, requirements.txt
=> update pydantic v2
